version: '2'
services:

  # Define a service for the postgres database
  db:
    image: postgres:9.3
    restart: always
    ports:
      - "5432:5432"

  # nginx
  nginx:
    build: ./nginx
    volumes:
      - .:/usr/src/app
    links:
      - django
    ports:
      - "80:80"

  # Define a service for the django app
  django:
    build: .
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
    links:
      - db
    depends_on:
      - db

