version: '2'
services:

  # nginx
  nginx:
    build: ./nginx
    volumes:
      - .:/usr/src/app
    links:
      - django
    ports:
      - "80:80"

  # Define a service for the django app
  django:
    build: .
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
#    links:
#      - db

  # Define a service for the postgres database
  db:
    image: postgres:9.3
