# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_report_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
